<?php

namespace DoctrineORMModule\Proxy\__CG__\Subscription\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \Subscription\Entity\Invoice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'uuid', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'invoiceNumber', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'referenceCode', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'user', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'ward', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'subscriptionType', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'amount', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'vatRate', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'vatAmount', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'subtotal', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'currency', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'status', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'paystackReference', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'createdOn', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'updatedOn', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'paidOn'];
        }

        return ['__isInitialized__', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'id', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'uuid', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'invoiceNumber', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'referenceCode', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'user', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'ward', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'subscriptionType', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'amount', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'vatRate', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'vatAmount', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'subtotal', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'currency', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'status', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'paystackReference', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'createdOn', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'updatedOn', '' . "\0" . 'Subscription\\Entity\\Invoice' . "\0" . 'paidOn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Invoice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUuid(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUuid', []);

        return parent::getUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUuid(string $uuid): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUuid', [$uuid]);

        return parent::setUuid($uuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceNumber(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceNumber', []);

        return parent::getInvoiceNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceNumber(string $invoiceNumber): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceNumber', [$invoiceNumber]);

        return parent::setInvoiceNumber($invoiceNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): \Authentication\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Authentication\Entity\User $user): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getWard(): \Ward\Entity\Ward
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWard', []);

        return parent::getWard();
    }

    /**
     * {@inheritDoc}
     */
    public function setWard(\Ward\Entity\Ward $ward): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWard', [$ward]);

        return parent::setWard($ward);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubscriptionType(): \Subscription\Entity\SubscriptionType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubscriptionType', []);

        return parent::getSubscriptionType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubscriptionType(\Subscription\Entity\SubscriptionType $subscriptionType): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubscriptionType', [$subscriptionType]);

        return parent::setSubscriptionType($subscriptionType);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', []);

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount(float $amount): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', [$amount]);

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatRate(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatRate', []);

        return parent::getVatRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setVatRate(float $vatRate): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVatRate', [$vatRate]);

        return parent::setVatRate($vatRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getVatAmount(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVatAmount', []);

        return parent::getVatAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setVatAmount(float $vatAmount): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVatAmount', [$vatAmount]);

        return parent::setVatAmount($vatAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtotal(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtotal', []);

        return parent::getSubtotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtotal(float $subtotal): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtotal', [$subtotal]);

        return parent::setSubtotal($subtotal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(string $currency): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaystackReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaystackReference', []);

        return parent::getPaystackReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaystackReference(?string $paystackReference): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaystackReference', [$paystackReference]);

        return parent::setPaystackReference($paystackReference);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn(\DateTime $createdOn): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn(\DateTime $updatedOn): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidOn(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidOn', []);

        return parent::getPaidOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaidOn(?\DateTime $paidOn): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaidOn', [$paidOn]);

        return parent::setPaidOn($paidOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferenceCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferenceCode', []);

        return parent::getReferenceCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferenceCode(?string $referenceCode): \Subscription\Entity\Invoice
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferenceCode', [$referenceCode]);

        return parent::setReferenceCode($referenceCode);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

}
