<?php

namespace DoctrineORMModule\Proxy\__CG__\Consultant\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ConsultantBooking extends \Consultant\Entity\ConsultantBooking implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'id', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'uuid', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'consultant', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'user', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'appointmentDate', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'preferredTime', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'reasonForVisit', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'status', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'createdOn', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'updatedOn'];
        }

        return ['__isInitialized__', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'id', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'uuid', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'consultant', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'user', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'appointmentDate', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'preferredTime', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'reasonForVisit', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'status', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'createdOn', '' . "\0" . 'Consultant\\Entity\\ConsultantBooking' . "\0" . 'updatedOn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ConsultantBooking $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUuid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUuid', []);

        return parent::getUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUuid(string $uuid): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUuid', [$uuid]);

        return parent::setUuid($uuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultant(): ?\Consultant\Entity\Consultant
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultant', []);

        return parent::getConsultant();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultant(\Consultant\Entity\Consultant $consultant): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultant', [$consultant]);

        return parent::setConsultant($consultant);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\Authentication\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Authentication\Entity\User $user): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppointmentDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppointmentDate', []);

        return parent::getAppointmentDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppointmentDate(\DateTime $appointmentDate): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppointmentDate', [$appointmentDate]);

        return parent::setAppointmentDate($appointmentDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferredTime(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferredTime', []);

        return parent::getPreferredTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferredTime(string $preferredTime): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferredTime', [$preferredTime]);

        return parent::setPreferredTime($preferredTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getReasonForVisit(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReasonForVisit', []);

        return parent::getReasonForVisit();
    }

    /**
     * {@inheritDoc}
     */
    public function setReasonForVisit(?string $reasonForVisit): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReasonForVisit', [$reasonForVisit]);

        return parent::setReasonForVisit($reasonForVisit);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn(\DateTime $createdOn): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn(\DateTime $updatedOn): \Consultant\Entity\ConsultantBooking
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

}
