<?php

namespace DoctrineORMModule\Proxy\__CG__\Authentication\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Jwt extends \Authentication\Entity\Jwt implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'id', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'signKey', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'refreshKey', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'verifyKkey', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'issuer', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'aud', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'secretKeyExpires', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'refreshKeyExpires', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'createdOn', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'updatedOn'];
        }

        return ['__isInitialized__', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'id', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'signKey', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'refreshKey', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'verifyKkey', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'issuer', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'aud', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'secretKeyExpires', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'refreshKeyExpires', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'createdOn', '' . "\0" . 'Authentication\\Entity\\Jwt' . "\0" . 'updatedOn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Jwt $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIssuer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssuer', []);

        return parent::getIssuer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssuer(string $issuer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssuer', [$issuer]);

        return parent::setIssuer($issuer);
    }

    /**
     * {@inheritDoc}
     */
    public function getAud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAud', []);

        return parent::getAud();
    }

    /**
     * {@inheritDoc}
     */
    public function setAud(string $aud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAud', [$aud]);

        return parent::setAud($aud);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn(\Datetime $createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn(\Datetime $updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignKey', []);

        return parent::getSignKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignKey(string $signKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignKey', [$signKey]);

        return parent::setSignKey($signKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefreshKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefreshKey', []);

        return parent::getRefreshKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefreshKey(string $refreshKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefreshKey', [$refreshKey]);

        return parent::setRefreshKey($refreshKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerifyKkey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerifyKkey', []);

        return parent::getVerifyKkey();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerifyKkey(string $verifyKkey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerifyKkey', [$verifyKkey]);

        return parent::setVerifyKkey($verifyKkey);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecretKeyExpires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecretKeyExpires', []);

        return parent::getSecretKeyExpires();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecretKeyExpires(string $secretKeyExpires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecretKeyExpires', [$secretKeyExpires]);

        return parent::setSecretKeyExpires($secretKeyExpires);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefreshKeyExpires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefreshKeyExpires', []);

        return parent::getRefreshKeyExpires();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefreshKeyExpires(string $refreshKeyExpires)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefreshKeyExpires', [$refreshKeyExpires]);

        return parent::setRefreshKeyExpires($refreshKeyExpires);
    }

}
