<?php

namespace DoctrineORMModule\Proxy\__CG__\Dyscalculia\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dyscalculia extends \Dyscalculia\Entity\Dyscalculia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'id', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'uuid', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'uniqueIdentifier', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'ward', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'assessmentDate', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'arithmeticScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'numberSenseScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'spatialReasoningScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'totalScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'severityLevel', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'notes'];
        }

        return ['__isInitialized__', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'id', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'uuid', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'uniqueIdentifier', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'ward', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'assessmentDate', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'arithmeticScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'numberSenseScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'spatialReasoningScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'totalScore', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'severityLevel', '' . "\0" . 'Dyscalculia\\Entity\\Dyscalculia' . "\0" . 'notes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dyscalculia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUuid', []);

        return parent::getUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUuid(string $uuid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUuid', [$uuid]);

        return parent::setUuid($uuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueIdentifier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueIdentifier', []);

        return parent::getUniqueIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function setUniqueIdentifier(string $uniqueIdentifier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUniqueIdentifier', [$uniqueIdentifier]);

        return parent::setUniqueIdentifier($uniqueIdentifier);
    }

    /**
     * {@inheritDoc}
     */
    public function getWard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWard', []);

        return parent::getWard();
    }

    /**
     * {@inheritDoc}
     */
    public function setWard(\Ward\Entity\Ward $ward)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWard', [$ward]);

        return parent::setWard($ward);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssessmentDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssessmentDate', []);

        return parent::getAssessmentDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssessmentDate(\DateTime $assessmentDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssessmentDate', [$assessmentDate]);

        return parent::setAssessmentDate($assessmentDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getArithmeticScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArithmeticScore', []);

        return parent::getArithmeticScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setArithmeticScore(int $arithmeticScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArithmeticScore', [$arithmeticScore]);

        return parent::setArithmeticScore($arithmeticScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberSenseScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberSenseScore', []);

        return parent::getNumberSenseScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberSenseScore(int $numberSenseScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberSenseScore', [$numberSenseScore]);

        return parent::setNumberSenseScore($numberSenseScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpatialReasoningScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpatialReasoningScore', []);

        return parent::getSpatialReasoningScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpatialReasoningScore(int $spatialReasoningScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpatialReasoningScore', [$spatialReasoningScore]);

        return parent::setSpatialReasoningScore($spatialReasoningScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalScore', []);

        return parent::getTotalScore();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalScore(int $totalScore)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalScore', [$totalScore]);

        return parent::setTotalScore($totalScore);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeverityLevel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeverityLevel', []);

        return parent::getSeverityLevel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeverityLevel(string $severityLevel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeverityLevel', [$severityLevel]);

        return parent::setSeverityLevel($severityLevel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', []);

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes(?string $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', [$notes]);

        return parent::setNotes($notes);
    }

}
