<?php

namespace DoctrineORMModule\Proxy\__CG__\Authentication\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserRefreshToken extends \Authentication\Entity\UserRefreshToken implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'id', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'refreshToken', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'userAgent', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'tokenId', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'userIp', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'userId', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'createdOn', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'updatedOn', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'expiresOn', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'uuid', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'refreshUid'];
        }

        return ['__isInitialized__', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'id', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'refreshToken', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'userAgent', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'tokenId', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'userIp', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'userId', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'createdOn', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'updatedOn', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'expiresOn', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'uuid', '' . "\0" . 'Authentication\\Entity\\UserRefreshToken' . "\0" . 'refreshUid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserRefreshToken $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRefreshToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefreshToken', []);

        return parent::getRefreshToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefreshToken(string $refreshToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefreshToken', [$refreshToken]);

        return parent::setRefreshToken($refreshToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAgent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAgent', []);

        return parent::getUserAgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAgent(string $userAgent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAgent', [$userAgent]);

        return parent::setUserAgent($userAgent);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIp', []);

        return parent::getUserIp();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserIp(string $userIp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserIp', [$userIp]);

        return parent::setUserIp($userIp);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(\Authentication\Entity\User $userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn(\Datetime $createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiresOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiresOn', []);

        return parent::getExpiresOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresOn(\Datetime $expiresOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresOn', [$expiresOn]);

        return parent::setExpiresOn($expiresOn);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefreshUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefreshUid', []);

        return parent::getRefreshUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefreshUid(string $refreshUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefreshUid', [$refreshUid]);

        return parent::setRefreshUid($refreshUid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUuid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUuid', []);

        return parent::getUuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUuid(string $uuid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUuid', [$uuid]);

        return parent::setUuid($uuid);
    }

    /**
     * {@inheritDoc}
     */
    public function getTokenId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTokenId', []);

        return parent::getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTokenId(string $tokenId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTokenId', [$tokenId]);

        return parent::setTokenId($tokenId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn(\Datetime $updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

}
