<?php

namespace DoctrineORMModule\Proxy\__CG__\General\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Settings extends \General\Entity\Settings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherAppKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherSecretKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherChannel', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherAppId', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherAppCluster', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'googleAPiKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'mailtrapToken', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'awsAccessKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'awsSecretKey'];
        }

        return ['__isInitialized__', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherAppKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherSecretKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherChannel', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherAppId', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'pusherAppCluster', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'googleAPiKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'mailtrapToken', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'awsAccessKey', '' . "\0" . 'General\\Entity\\Settings' . "\0" . 'awsSecretKey'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Settings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPusherAppKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPusherAppKey', []);

        return parent::getPusherAppKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPusherAppKey(string $pusherAppKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPusherAppKey', [$pusherAppKey]);

        return parent::setPusherAppKey($pusherAppKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPusherSecretKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPusherSecretKey', []);

        return parent::getPusherSecretKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPusherSecretKey(string $pusherSecretKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPusherSecretKey', [$pusherSecretKey]);

        return parent::setPusherSecretKey($pusherSecretKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPusherAppId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPusherAppId', []);

        return parent::getPusherAppId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPusherAppId(string $pusherAppId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPusherAppId', [$pusherAppId]);

        return parent::setPusherAppId($pusherAppId);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleAPiKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleAPiKey', []);

        return parent::getGoogleAPiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleAPiKey(string $googleAPiKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleAPiKey', [$googleAPiKey]);

        return parent::setGoogleAPiKey($googleAPiKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getPusherAppCluster()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPusherAppCluster', []);

        return parent::getPusherAppCluster();
    }

    /**
     * {@inheritDoc}
     */
    public function setPusherAppCluster(string $pusherAppCluster)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPusherAppCluster', [$pusherAppCluster]);

        return parent::setPusherAppCluster($pusherAppCluster);
    }

    /**
     * {@inheritDoc}
     */
    public function getPusherChannel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPusherChannel', []);

        return parent::getPusherChannel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPusherChannel(string $pusherChannel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPusherChannel', [$pusherChannel]);

        return parent::setPusherChannel($pusherChannel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailtrapToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailtrapToken', []);

        return parent::getMailtrapToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailtrapToken(string $mailtrapToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailtrapToken', [$mailtrapToken]);

        return parent::setMailtrapToken($mailtrapToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getAwsAccessKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAwsAccessKey', []);

        return parent::getAwsAccessKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setAwsAccessKey(string $awsAccessKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAwsAccessKey', [$awsAccessKey]);

        return parent::setAwsAccessKey($awsAccessKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getAwsSecretKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAwsSecretKey', []);

        return parent::getAwsSecretKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setAwsSecretKey(string $awsSecretKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAwsSecretKey', [$awsSecretKey]);

        return parent::setAwsSecretKey($awsSecretKey);
    }

}
