<?php

namespace DoctrineORMModule\Proxy\__CG__\Wallet\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Refferal extends \Wallet\Entity\Refferal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'id', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalUid', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'user', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalCode', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalEmail', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalPhone', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'isRegistered', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referedAccount', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'registeredOn', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'createdOn', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'updatedOn'];
        }

        return ['__isInitialized__', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'id', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalUid', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'user', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalCode', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalEmail', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referalPhone', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'isRegistered', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'referedAccount', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'registeredOn', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'createdOn', '' . "\0" . 'Wallet\\Entity\\Refferal' . "\0" . 'updatedOn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Refferal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferalUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferalUid', []);

        return parent::getReferalUid();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferalCode', []);

        return parent::getReferalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferalEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferalEmail', []);

        return parent::getReferalEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferalPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferalPhone', []);

        return parent::getReferalPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRegistered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRegistered', []);

        return parent::getIsRegistered();
    }

    /**
     * {@inheritDoc}
     */
    public function getReferedAccount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferedAccount', []);

        return parent::getReferedAccount();
    }

    /**
     * {@inheritDoc}
     */
    public function getRegisteredOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegisteredOn', []);

        return parent::getRegisteredOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', []);

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedOn', []);

        return parent::getUpdatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setReferalUid($referalUid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferalUid', [$referalUid]);

        return parent::setReferalUid($referalUid);
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setReferalCode($referalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferalCode', [$referalCode]);

        return parent::setReferalCode($referalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function setReferalEmail($referalEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferalEmail', [$referalEmail]);

        return parent::setReferalEmail($referalEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function setReferalPhone($referalPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferalPhone', [$referalPhone]);

        return parent::setReferalPhone($referalPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRegistered($isRegistered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRegistered', [$isRegistered]);

        return parent::setIsRegistered($isRegistered);
    }

    /**
     * {@inheritDoc}
     */
    public function setReferedAccount($referedAccount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferedAccount', [$referedAccount]);

        return parent::setReferedAccount($referedAccount);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegisteredOn($registeredOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegisteredOn', [$registeredOn]);

        return parent::setRegisteredOn($registeredOn);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedOn($createdOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedOn', [$createdOn]);

        return parent::setCreatedOn($createdOn);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedOn($updatedOn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedOn', [$updatedOn]);

        return parent::setUpdatedOn($updatedOn);
    }

}
