<?php

/**
 * ============================================================================
 * DYXI Platform - GameAdmin Subsystem
 * File: GameForm.php
 * ============================================================================
 * Description: Form representation for creating & editing Game entities. Collects
 * title, unique identifier, category, launch URL, extensive description text,
 * multiple markdown (.md) file uploads, and optional tags/JSON configuration.
 * Summary is auto-generated by Gemini AI from description & uploaded .md files.
 * ============================================================================
 */

declare(strict_types=1);

namespace GameAdmin\Form;

use GameAdmin\Form\InputFilter\GameInputFilter;
use Laminas\Form\Element;
use Laminas\Form\Form;

/**
 * Form for Game Entity creation and editing.
 */
class GameForm extends Form
{
    private array $gameTypeOptions;
    private array $curriculumOptions;

    /**
     * GameForm Constructor.
     *
     * @param array $gameTypeOptions Array of GameType select options.
     * @param array $curriculumOptions Array of Curriculum select options.
     * @param string $name Form instance name.
     */
    public function __construct(array $gameTypeOptions = [], array $curriculumOptions = [], $name = 'game_form')
    {
        parent::__construct($name);

        $this->gameTypeOptions   = $gameTypeOptions;
        $this->curriculumOptions = $curriculumOptions;

        $this->setAttributes([
            'method'  => 'POST',
            'enctype' => 'multipart/form-data',
            'class'   => 'ga-game-form',
        ]);

        $this->setInputFilter(new GameInputFilter());
        $this->addElements();
    }

    /**
     * Adds form fields and elements.
     */
    private function addElements(): void
    {
        // Title Field
        $this->add([
            'name' => 'title',
            'type' => Element\Text::class,
            'options' => [
                'label' => 'Game Title',
            ],
            'attributes' => [
                'class'       => 'ga-form-control',
                'placeholder' => 'e.g. Speed Reader Quest 3D',
                'required'    => 'required',
            ],
        ]);

        // Unique Identifier Field
        $this->add([
            'name' => 'uniqueIdentifier',
            'type' => Element\Text::class,
            'options' => [
                'label' => 'Unique String Identifier',
            ],
            'attributes' => [
                'class'       => 'ga-form-control',
                'placeholder' => 'e.g. game_speed_reader_v1',
                'required'    => 'required',
            ],
        ]);

        // Game Type Select Field
        $this->add([
            'name' => 'gameTypeId',
            'type' => Element\Select::class,
            'options' => [
                'label'         => 'Game Category / Intervention Type',
                'value_options' => $this->gameTypeOptions,
                'empty_option'  => '-- Select Game Category --',
            ],
            'attributes' => [
                'class'    => 'ga-form-control',
                'required' => 'required',
            ],
        ]);

        // Curriculum Select Field
        $this->add([
            'name' => 'curriculumId',
            'type' => Element\Select::class,
            'options' => [
                'label'         => 'Target Curriculum (Optional)',
                'value_options' => $this->curriculumOptions,
                'empty_option'  => '-- None / General Curriculum --',
            ],
            'attributes' => [
                'class' => 'ga-form-control',
            ],
        ]);

        // Game Absolute Launch URL Field
        $this->add([
            'name' => 'gameAbsoluteUrl',
            'type' => Element\Text::class,
            'options' => [
                'label' => 'Absolute Launch URL',
            ],
            'attributes' => [
                'class'       => 'ga-form-control',
                'placeholder' => 'e.g. /games/speed-reader-v1 or https://engine.dyxi.app/launch/v1',
                'required'    => 'required',
            ],
        ]);

        // Searchable Tags / Keywords Field
        $this->add([
            'name' => 'tags',
            'type' => Element\Text::class,
            'options' => [
                'label' => 'Search Engine Keywords & Tags (Auto-generated by Gemini if empty)',
            ],
            'attributes' => [
                'class'       => 'ga-form-control',
                'placeholder' => 'e.g. early-childhood-education, dyslexia, phonics, adhd, executive-function',
            ],
        ]);

        // Multiple Markdown (.md) Files Upload Input Field
        $this->add([
            'name' => 'mdFiles',
            'type' => Element\File::class,
            'options' => [
                'label' => 'Upload Markdown (.md) Document Files (Content will be extracted & appended to description)',
            ],
            'attributes' => [
                'class'    => 'ga-form-control',
                'multiple' => 'multiple',
                'accept'   => '.md,.markdown,text/markdown,text/plain',
                'id'       => 'ga-md-files-input',
            ],
        ]);

        // Detailed Description Field (Huge text data input used by Gemini to generate AI summary and tags)
        $this->add([
            'name' => 'description',
            'type' => Element\Textarea::class,
            'options' => [
                'label' => 'Detailed Game Description (Or upload .md files above)',
            ],
            'attributes' => [
                'class'       => 'ga-form-control',
                'rows'        => 8,
                'placeholder' => 'Enter comprehensive diagnostic and educational content here, or upload one or more .md files above. Gemini AI will analyze the combined text to generate an AI summary and extract search tags...',
            ],
        ]);

        // Custom JSON Configuration Field
        $this->add([
            'name' => 'customConfig',
            'type' => Element\Textarea::class,
            'options' => [
                'label' => 'Custom Configuration (JSON)',
            ],
            'attributes' => [
                'class'       => 'ga-form-control',
                'rows'        => 3,
                'placeholder' => '{"difficulty": "adaptive", "maxTime": 300, "telemetryMode": "full"}',
            ],
        ]);

        // CSRF Protection Token
        $this->add([
            'name' => 'csrf',
            'type' => Element\Csrf::class,
            'options' => [
                'csrf_options' => [
                    'timeout' => 600,
                ],
            ],
        ]);

        // Submit Button
        $this->add([
            'name' => 'submit',
            'type' => Element\Submit::class,
            'attributes' => [
                'value' => 'Save Game Entity & Process AI Summaries',
                'class' => 'ga-btn-primary',
            ],
        ]);
    }
}
