<?php
?>

<div class="card-header pb-0 text-left bg-transparent">
    <h3 class="font-weight-bolder text-info text-gradient">Reset Password</h3>
    <!-- <p class="mb-0">Enter your email and password to sign in</p> -->
</div>
<div id="ress" class="card-body">
    <!-- <form role="form"> -->
    <label>Phone or Email </label>
    <div class="mb-3">
        <input v-model="email" type="email" class="form-control" ref="phoneOrEmail" placeholder="Phone or Email" aria-label="Email" aria-describedby="email-addon">
    </div>

    <div v-if="isSubmitting">
        <i class="fas fa-spinner fs-3x"></i>
    </div>
    <div v-else>
        <div class="text-center">
            <button @click="reset" type="button" class="btn bg-gradient-info w-100 mt-4 mb-0">Reset Password</button>
        </div>
    </div>
    <!-- </form> -->

</div>
<div class="card-footer text-center pt-0 px-lg-2 px-1">
    <p class="mb-4 text-sm mx-auto">

        <a href="<?= $this->url("authentication") ?>" class="text-info text-gradient font-weight-bold">Back To Login</a>
    </p>
</div>

<script>
    const app = Vue.createApp({
        data() {
            return {
                isSubmitting: false,
                email: ""
            }
        },
        methods: {
            reset() {
                this.isSubmitting = true;
                if (this.email == "") {
                    Swal.fire({
                        icon: "error",
                        title: "Empty field",
                        text: "Email Field is empty"
                    })
                } else {
                    let formData = new FormData();
                    formData.append("email", this.email);
                    axios.post("/auth/reset", formData).then((result) => {
                        if (result.status == 201) {
                            Swal.fire({
                                icon: "success",
                                title: "Reset Link sent",
                                test: "A reset link has been sent to you email"
                            });
                            this.isSubmitting = false;
                        }
                    }).catch((err) => {

                    });
                }

            }
        },
    });
    app.mount("#ress");
</script>