<?php

namespace Subscription\Service;

class TokenDecryptionService
{
    private string $centralHexKey;

    public function __construct(?string $centralHexKey = null)
    {
        $this->centralHexKey = trim(
            $centralHexKey
                ?: getenv('CENTRAL_HEX_KEY')
                ?: getenv('CENTRAL_KEY_HEX')
                ?: 'a7f9a46f8a2f78c7d3425a647d4def90ddd09c257d75d7afe15b1b9428ddb7ab'
        );

        // Validate the key immediately.
        if (
            strlen($this->centralHexKey) !== 64 ||
            !ctype_xdigit($this->centralHexKey)
        ) {
            throw new \InvalidArgumentException(
                'CENTRAL_HEX_KEY must contain exactly 64 hexadecimal characters.'
            );
        }
    }

    /**
     * Decrypt a token generated by Qt TokenManager::createToken()
     *
     * Token structure:
     *
     *   [16-byte IV][AES-256-CBC ciphertext]
     *
     * The complete binary structure is Base64 URL encoded
     * without trailing "=" characters.
     */
    public function decryptToken(string $token): array
    {
        $token = trim($token);

        if ($token === '') {
            throw new \InvalidArgumentException(
                'Token is required.'
            );
        }

        /*
         * ---------------------------------------------------------
         * 1. Convert hexadecimal key to binary
         * ---------------------------------------------------------
         */

        $binaryKey = hex2bin($this->centralHexKey);

        if ($binaryKey === false || strlen($binaryKey) !== 32) {
            throw new \RuntimeException(
                'Invalid AES-256 key.'
            );
        }

        /*
         * ---------------------------------------------------------
         * 2. Convert URL-safe Base64 to standard Base64
         * ---------------------------------------------------------
         *
         * Qt:
         *
         * QByteArray::Base64UrlEncoding |
         * QByteArray::OmitTrailingEquals
         *
         * produces:
         *
         *   - instead of +
         *   _ instead of /
         *   no "=" padding
         */

        $base64Token = strtr($token, '-_', '+/');

        $remainder = strlen($base64Token) % 4;

        if ($remainder === 1) {
            throw new \InvalidArgumentException(
                'Invalid Base64 token length.'
            );
        }

        if ($remainder !== 0) {
            $base64Token .= str_repeat('=', 4 - $remainder);
        }

        /*
         * ---------------------------------------------------------
         * 3. Decode Base64
         * ---------------------------------------------------------
         */

        $decodedBinary = base64_decode($base64Token, true);

        if ($decodedBinary === false) {
            throw new \InvalidArgumentException(
                'Invalid Base64 token.'
            );
        }

        /*
         * ---------------------------------------------------------
         * 4. Validate token structure
         * ---------------------------------------------------------
         *
         * 16 bytes IV
         * +
         * at least 16 bytes ciphertext
         */

        if (strlen($decodedBinary) < 32) {
            throw new \InvalidArgumentException(
                'Invalid token structure. Decoded length: '
                . strlen($decodedBinary)
            );
        }

        /*
         * ---------------------------------------------------------
         * 5. Extract IV and ciphertext
         * ---------------------------------------------------------
         */

        $iv = substr($decodedBinary, 0, 16);
        $ciphertext = substr($decodedBinary, 16);

        if (strlen($iv) !== 16) {
            throw new \RuntimeException(
                'Invalid IV length.'
            );
        }

        if (strlen($ciphertext) === 0) {
            throw new \RuntimeException(
                'Ciphertext is empty.'
            );
        }

        /*
         * AES-CBC ciphertext must be a multiple of
         * the AES block size.
         */

        if (strlen($ciphertext) % 16 !== 0) {
            throw new \RuntimeException(
                'Invalid ciphertext length: '
                . strlen($ciphertext)
            );
        }

        /*
         * ---------------------------------------------------------
         * 6. AES-256-CBC decrypt
         * ---------------------------------------------------------
         */

        $decryptedString = openssl_decrypt(
            $ciphertext,
            'AES-256-CBC',
            $binaryKey,
            OPENSSL_RAW_DATA,
            $iv
        );

        if ($decryptedString === false) {
            throw new \RuntimeException(
                'AES-256-CBC decryption failed. '
                . 'The key, IV, or ciphertext does not match.'
            );
        }

        /*
         * ---------------------------------------------------------
         * 7. Parse JSON payload
         * ---------------------------------------------------------
         */

        $payload = json_decode(
            $decryptedString,
            true
        );

        if (!is_array($payload)) {
            /*
             * Support strings such as:
             *
             * userId=123,wardId=456
             */

            $payload = [];

            parse_str(
                str_replace(',', '&', $decryptedString),
                $payload
            );

            if (empty($payload)) {
                $payload = [
                    'raw' => $decryptedString
                ];
            }
        }

        /*
         * ---------------------------------------------------------
         * 8. Normalize IDs
         * ---------------------------------------------------------
         */

        if (
            !isset($payload['userId']) &&
            isset($payload['user_id'])
        ) {
            $payload['userId'] = $payload['user_id'];
        }

        if (
            !isset($payload['wardId']) &&
            isset($payload['ward_id'])
        ) {
            $payload['wardId'] = $payload['ward_id'];
        }

        return [
            'original_string' => $decryptedString,
            'payload' => $payload,
            'user_id' => $payload['userId'] ?? null,
            'ward_id' => $payload['wardId'] ?? null,
        ];
    }

    /**
     * Generate a token compatible with the Qt TokenManager.
     */
    public function encryptToken(array|string $data): string
    {
        $binaryKey = hex2bin($this->centralHexKey);

        if ($binaryKey === false || strlen($binaryKey) !== 32) {
            throw new \RuntimeException(
                'Invalid AES-256 key.'
            );
        }

        $plainText = is_array($data)
            ? json_encode(
                $data,
                JSON_UNESCAPED_SLASHES
                    | JSON_UNESCAPED_UNICODE
                    | JSON_THROW_ON_ERROR
            )
            : (string) $data;

        /*
         * AES block size = 16 bytes
         */
        $iv = random_bytes(16);

        $ciphertext = openssl_encrypt(
            $plainText,
            'AES-256-CBC',
            $binaryKey,
            OPENSSL_RAW_DATA,
            $iv
        );

        if ($ciphertext === false) {
            throw new \RuntimeException(
                'AES encryption failed.'
            );
        }

        /*
         * Same structure as Qt:
         *
         * IV + ciphertext
         */
        $tokenData = $iv . $ciphertext;

        /*
         * URL-safe Base64 without "=".
         *
         * This matches:
         *
         * QByteArray::Base64UrlEncoding |
         * QByteArray::OmitTrailingEquals
         */
        return rtrim(
            strtr(
                base64_encode($tokenData),
                '+/',
                '-_'
            ),
            '='
        );
    }

    public function getCentralHexKey(): string
    {
        return $this->centralHexKey;
    }
}
